name: Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get latest build run ID
        id: get_run_id
        run: |
          RUN_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?branch=main&event=pull_request&status=completed" | \
            jq -r '.workflow_runs[0].id')
          echo "::set-output name=run_id::$RUN_ID"

      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          run-id: ${{ steps.get_run_id.outputs.run_id }}
          name: build-latest
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github-token: ${{ github.token }}
          publish_dir: ./build
