name: Deploy Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check for build-latest artifact
        run: |
          ARTIFACT_URL=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[] | select(.name == "build-latest") | .archive_download_url')
          if [ -z "$ARTIFACT_URL" ]; then
            echo "Artifact build-latest not found"
            exit 1
          else
            echo "Artifact build-latest found at $ARTIFACT_URL"
          fi

      - name: Download build artefact
        uses: actions/download-artifact@v4
        with:
          name: build-latest
          path: ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
